import json
from typing import Dict, Any
from graph.state import AnalysisState
from tools.llm_clients import call_gemini_llm

def analyze_ai_probability(state: AnalysisState) -> Dict[str, Any]:
    """
    Agent 5: AI Assistance Analysis Agent
    Estimates the probability that the codebase was heavily assisted or generated by AI.
    """
    print("--- [Agent: AI Authenticity] Evaluating authorship probability ---")
    
    files = state.get("files", [])
    if not files:
        return {
            "ai_probability": {
                "human_probability": 1.0,
                "ai_probability": 0.0,
                "confidence": 0.0,
                "reasoning": "No files provided."
            }
        }

    # Prepare context
    code_context = ""
    for file_obj in files:
        filename = file_obj.get("filename", "unknown_file")
        content = file_obj.get("content", "")
        code_context += f"\n--- File: {filename} ---\n{content}\n"

    prompt = f"""
    You are an AI Authorship Detection Model (acting as Gemma 4 31B).
    Analyze the following source code to estimate the probability that it was written by a Large Language Model versus a human developer.

    Evaluate based on these 3 Stages:
    Stage 1 - Feature Extraction: Look at average function length, variable naming entropy (are names too perfect?), and comment density (are there overly descriptive, textbook-style comments?).
    Stage 2 - Static Pattern Analysis: Look for highly repetitive structures, perfectly uniform coding styles, and standard LLM boilerplate templates.
    Stage 3 - Assessment: Synthesize these signals.

    Return ONLY a valid JSON object. Do not include markdown code blocks.
    The object must exactly match this structure:
    {{
        "human_probability": <float between 0.0 and 1.0>,
        "ai_probability": <float between 0.0 and 1.0>,
        "confidence": <float between 0.0 and 1.0>,
        "reasoning": "A concise explanation of which features led to this conclusion."
    }}

    Note: human_probability + ai_probability must equal 1.0.

    Source Code Context:
    {code_context}
    """

    try:
        # Using the standard client. In production, you might route this specific 
        # call to a fine-tuned Gemma endpoint as per your TRD.
        response_text = call_gemini_llm(prompt=prompt, model_name="gemma-4-31b-it")
        
        # Clean and parse JSON
        clean_json_str = response_text.strip().removeprefix("```json").removesuffix("```").strip()
        authenticity_data = json.loads(clean_json_str)
        
        # Ensure fallback safety for probabilities
        ai_prob = authenticity_data.get("ai_probability", 0.0)
        print(f"-> Authenticity Analysis Complete. AI Probability: {ai_prob * 100:.1f}%")
        
        return {
            "ai_probability": authenticity_data
        }

    except Exception as e:
        print(f"[-] AI Authenticity Agent Error: {str(e)}")
        # Safe fallback: Assume human if detection fails
        return {
            "ai_probability": {
                "human_probability": 1.0,
                "ai_probability": 0.0,
                "confidence": 0.0,
                "reasoning": "Analysis failed due to an error."
            }
        }