import os
from typing import Any, Dict, Optional
import google.generativeai as genai

# Configure the SDK globally using either GOOGLE_API_KEY or GEMINI_API_KEY
api_key = os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")
if api_key:
    genai.configure(api_key=api_key)

def call_gemini_llm(
    prompt: str, 
    model_name: str = "gemma-4-31b-it", 
    generation_config: Optional[Dict[str, Any]] = None
) -> str:
    """
    Central helper tool to route prompts to the Google Gemini API.
    Enforces structural configurations like system instructions or JSON formatting flags.
    """
    if not (os.getenv("GOOGLE_API_KEY") or os.getenv("GEMINI_API_KEY")):
        raise ValueError("Missing GOOGLE_API_KEY or GEMINI_API_KEY environment variable. Please check your .env file.")
        
    # Default settings to maintain deterministic and structured agent analysis
    default_config = {
        "temperature": 0.2,
        "top_p": 0.95,
    }
    
    # Gemma models hosted on the API do not natively support the strict response_mime_type flag
    if "json" in prompt.lower() and model_name.startswith("gemini"):
        default_config["response_mime_type"] = "application/json"
    
    if generation_config:
        default_config.update(generation_config)
        
    try:
        model = genai.GenerativeModel(
            model_name=model_name,
            generation_config=default_config
        )
        response = model.generate_content(prompt)
        text = response.text
        
        # Robust JSON extraction for models that output conversational wrapper text
        if "json" in prompt.lower():
            import re
            import json
            import ast
            
            def attempt_parse(s: str):
                try:
                    return json.loads(s), s
                except json.JSONDecodeError:
                    try:
                        # Fix unquoted keys (e.g. { key: "value" } -> { "key": "value" }) generated by LLMs confusing JS with JSON
                        import re
                        fixed_s = re.sub(r'([{,]\s*)([a-zA-Z_][a-zA-Z0-9_]*)\s*:', r'\1"\2":', s)
                        
                        try:
                            return json.loads(fixed_s), fixed_s
                        except json.JSONDecodeError:
                            pass
                            
                        safe_s = fixed_s.replace("null", "None").replace("true", "True").replace("false", "False")
                        python_obj = ast.literal_eval(safe_s)
                        return python_obj, json.dumps(python_obj)
                    except Exception:
                        return None, None

            def extract_json_structures(s: str):
                start_indices = [i for i, char in enumerate(s) if char in ('{', '[')]
                for start_idx in start_indices:
                    stack = []
                    in_string = False
                    escape = False
                    
                    for i in range(start_idx, len(s)):
                        char = s[i]
                        if not escape and char == '"':
                            in_string = not in_string
                        if not in_string:
                            if char in ('{', '['):
                                stack.append(char)
                            elif char == '}':
                                if stack and stack[-1] == '{': stack.pop()
                            elif char == ']':
                                if stack and stack[-1] == '[': stack.pop()
                            if not stack:
                                yield s[start_idx:i+1]
                                break
                        escape = (char == '\\' and not escape)

            extracted_text = text
            valid_candidates = []
            
            # 1. Try markdown blocks first
            blocks = re.findall(r'```(?:json)?\s*(.*?)\s*```', text, re.DOTALL)
            for block in blocks:
                for clean_block in extract_json_structures(block.strip()):
                    obj, valid_str = attempt_parse(clean_block)
                    if obj is not None:
                        valid_candidates.append(valid_str)
                    
            # 2. Try the whole text using the bracket generator
            for clean_text in extract_json_structures(text.strip()):
                obj, valid_str = attempt_parse(clean_text)
                if obj is not None:
                    valid_candidates.append(valid_str)
                    
            if valid_candidates:
                # Return the largest valid JSON structure (the actual payload, not inline snippets like ["UI"])
                return max(valid_candidates, key=len)
            
            # If all fails, print debug and return raw
            print(f"--- [DEBUG LLM CLIENT] RAW LLM TEXT FAILED ALL EXTRACTION ---\n{text}\n-------------------")
                    
        return text
    except Exception as e:
        print(f"[-] LLM Client Exception: Error communicating with Gemini API: {str(e)}")
        raise e